artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?id=1M71W_DvMCCmRL373qVG3-8dHJtiy8e4H&export=download
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Churn_Modelling.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Churn_Modelling.csv
  preprocessor_name: preprocessor.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  model_params:  # Add model hyperparameters here
    param1: value1
    param2: value2

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  confusion_matrix_file: artifacts/model_evaluation/confusion_matrix.png  # Path to save confusion matrix
  roc_curve_file: artifacts/model_evaluation/roc_curve.png  # Path to save ROC curve data

mlflow_config:
  mlflow_uri: "https://dagshub.com/shreyojitdas95/Deploying-Customer-Churn-model.mlflow"  # MLflow tracking server URI
  model_registry: "models:/LightGBM/1"  # Example for model registry URI
